name: Run tests on changes made to the master branch

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run_simple_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the master branch
        uses: actions/checkout@v3

      - name: Install the python package
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install my package
        run: pip install .

      - name: Run the tests
        run: pytest -v
